$axure.loadCurrentPage({
  "url":"定时退出.html",
  "generationDate":new Date(1392372079988.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fd9d4e4fd5a34772bdd6656009c12f6c",
    "type":"Axure:Page",
    "name":"定时退出",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a9fbfe5ad5034570801c67c2438376d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":378,
              "y":50},
            "size":{
              "width":320,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11177f03fc2f4ccdbb6695a31779fa02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":378,
                  "y":50},
                "size":{
                  "width":320,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定时退出/u0.png"}},
{
          "id":"9af78c5a87e4423c806f64390a0d682c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":378,
              "y":50},
            "size":{
              "width":320,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a468ecda1dc94bb1b0a797a09768c472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":378,
                  "y":50},
                "size":{
                  "width":320,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/节目列表优化/u25.png"}},
{
          "id":"1d61cde8dca4408cb59e2fa1e5e3b7e1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":100},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定时退出/u4_line.png"}},
{
          "id":"e2f4a5ea628140cb81a141765f489300",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":158},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定时退出/u4_line.png"}},
{
          "id":"d5f2bb0157684105b88e83464e8d8115",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":220},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定时退出/u4_line.png"}},
{
          "id":"3587d35be3be4089b5eea9d11b1be5e5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":286},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定时退出/u4_line.png"}},
{
          "id":"338563852026473e9f0c5cb93fcb7ec9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":344},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定时退出/u4_line.png"}},
{
          "id":"01d07699aa7a40d786dfad7066a0b422",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":406},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定时退出/u4_line.png"}},
{
          "id":"7d05681efd0b4a94867ec39cc5a18013",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "location":{
              "x":439,
              "y":73},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30aab6a0747d437d8095cd9c35597b2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "location":{
                  "x":439,
                  "y":73},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6df7d2dcb03042fab083ce95777f5d72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3366,
              "opacity":1},
            "location":{
              "x":649,
              "y":73},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7e68a8f4d5749d18b13f25cc7483eb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1},
                "location":{
                  "x":649,
                  "y":73},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"666d0175141045ea8705c6926c1e84f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":384,
              "y":126},
            "size":{
              "width":64,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62b4d4e12a0c4b428eda6b1ea93c43ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":384,
                  "y":126},
                "size":{
                  "width":64,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5e12e291676471d80c65e6e6334ed1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":384,
              "y":182},
            "size":{
              "width":64,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bdfaacb289b4dcc91bef44d27734338",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":384,
                  "y":182},
                "size":{
                  "width":64,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eba26d813ec34681bc46c646f46957d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":384,
              "y":248},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039e93364af24b9f9dfa56b1e1d810a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":384,
                  "y":248},
                "size":{
                  "width":76,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82165dbf9f714f9694483ca3a7dfedab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":384,
              "y":312},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b631ae662cc44d6c8cf55afdf7d85a5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":384,
                  "y":312},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1c1e98445bd436cac6632f47378b945",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":470},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定时退出/u4_line.png"}},
{
          "id":"825b6162925d417db8c9ebb6cabd3ee0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":382,
              "y":366},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4b254b7bde44c8c8d71bc3c5088ec31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":382,
                  "y":366},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3e37bd7e9a34aefb6b6ee25bc02f502",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":384,
              "y":426},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daf55fccf8be48afafadc4f0533d9dc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":384,
                  "y":426},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef744d006fe741eb836a07ea4fa3ba65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":648,
              "y":243},
            "size":{
              "width":41,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec06deee08b14042840d667b8bfb790c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":648,
                  "y":243},
                "size":{
                  "width":41,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f7df190176441dbbb69526650665e03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":22,
              "y":686},
            "size":{
              "width":300,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df4a88127e14fd5a15cfe0082dfcde4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":22,
                  "y":686},
                "size":{
                  "width":300,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82b91d7478e04c84a7b64d350f0e2acb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":86},
            "size":{
              "width":69,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/定时退出/u31_start.png",
            "end~":"images/定时退出/u31_end.png",
            "line~":"images/定时退出/u31_line.png"}},
{
          "id":"bb06b163843041b7b7fa2062c3b22b88",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":689,
              "y":77.5},
            "size":{
              "width":69,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/定时退出/u31_start.png",
            "end~":"images/定时退出/u31_end.png",
            "line~":"images/定时退出/u31_line.png"}},
{
          "id":"95740d6d4e524a1ab86658911d1408d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":356,
              "height":633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f70ccc15f31442d4a999d44c9dee37ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":356,
                  "height":633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放器三合一/u2.jpg"}},
{
          "id":"4c08aac0edd84fc392c5887366c1a1cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":764,
              "y":60},
            "size":{
              "width":437,
              "height":777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eba0bfe1b8bf4ccd96100b42ecca25df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":764,
                  "y":60},
                "size":{
                  "width":437,
                  "height":777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放器三合一/u4.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "a9fbfe5ad5034570801c67c2438376d6":{
      "scriptId":"u0"},
    "11177f03fc2f4ccdbb6695a31779fa02":{
      "scriptId":"u1"},
    "9af78c5a87e4423c806f64390a0d682c":{
      "scriptId":"u2"},
    "a468ecda1dc94bb1b0a797a09768c472":{
      "scriptId":"u3"},
    "1d61cde8dca4408cb59e2fa1e5e3b7e1":{
      "scriptId":"u4"},
    "e2f4a5ea628140cb81a141765f489300":{
      "scriptId":"u5"},
    "d5f2bb0157684105b88e83464e8d8115":{
      "scriptId":"u6"},
    "3587d35be3be4089b5eea9d11b1be5e5":{
      "scriptId":"u7"},
    "338563852026473e9f0c5cb93fcb7ec9":{
      "scriptId":"u8"},
    "01d07699aa7a40d786dfad7066a0b422":{
      "scriptId":"u9"},
    "7d05681efd0b4a94867ec39cc5a18013":{
      "scriptId":"u10"},
    "30aab6a0747d437d8095cd9c35597b2b":{
      "scriptId":"u11"},
    "6df7d2dcb03042fab083ce95777f5d72":{
      "scriptId":"u12"},
    "d7e68a8f4d5749d18b13f25cc7483eb5":{
      "scriptId":"u13"},
    "666d0175141045ea8705c6926c1e84f0":{
      "scriptId":"u14"},
    "62b4d4e12a0c4b428eda6b1ea93c43ef":{
      "scriptId":"u15"},
    "c5e12e291676471d80c65e6e6334ed1f":{
      "scriptId":"u16"},
    "1bdfaacb289b4dcc91bef44d27734338":{
      "scriptId":"u17"},
    "eba26d813ec34681bc46c646f46957d9":{
      "scriptId":"u18"},
    "039e93364af24b9f9dfa56b1e1d810a9":{
      "scriptId":"u19"},
    "82165dbf9f714f9694483ca3a7dfedab":{
      "scriptId":"u20"},
    "b631ae662cc44d6c8cf55afdf7d85a5c":{
      "scriptId":"u21"},
    "e1c1e98445bd436cac6632f47378b945":{
      "scriptId":"u22"},
    "825b6162925d417db8c9ebb6cabd3ee0":{
      "scriptId":"u23"},
    "e4b254b7bde44c8c8d71bc3c5088ec31":{
      "scriptId":"u24"},
    "c3e37bd7e9a34aefb6b6ee25bc02f502":{
      "scriptId":"u25"},
    "daf55fccf8be48afafadc4f0533d9dc5":{
      "scriptId":"u26"},
    "ef744d006fe741eb836a07ea4fa3ba65":{
      "scriptId":"u27"},
    "ec06deee08b14042840d667b8bfb790c":{
      "scriptId":"u28"},
    "9f7df190176441dbbb69526650665e03":{
      "scriptId":"u29"},
    "7df4a88127e14fd5a15cfe0082dfcde4":{
      "scriptId":"u30"},
    "82b91d7478e04c84a7b64d350f0e2acb":{
      "scriptId":"u31"},
    "bb06b163843041b7b7fa2062c3b22b88":{
      "scriptId":"u32"},
    "95740d6d4e524a1ab86658911d1408d2":{
      "scriptId":"u33"},
    "f70ccc15f31442d4a999d44c9dee37ca":{
      "scriptId":"u34"},
    "4c08aac0edd84fc392c5887366c1a1cc":{
      "scriptId":"u35"},
    "eba0bfe1b8bf4ccd96100b42ecca25df":{
      "scriptId":"u36"}}});