$axure.loadCurrentPage({
  "url":"查看列表_1.html",
  "generationDate":new Date(1392372077871.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"414185e7bdf6441eb053f3d4106f01c5",
    "type":"Axure:Page",
    "name":"查看列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"416de2752ec04666a57a5fec439505e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":30},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6655fce98b254264949cdcbed4fe18ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":30},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "416de2752ec04666a57a5fec439505e2":{
      "scriptId":"u0"},
    "6655fce98b254264949cdcbed4fe18ca":{
      "scriptId":"u1"}}});