$axure.loadCurrentPage({
  "url":"预约.html",
  "generationDate":new Date(1392283801202.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"646d76b6ccfc4f5aaa204235ecc79aae",
    "type":"Axure:Page",
    "name":"预约",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b94cae60e0604f7990541efc34e8ae22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":730,
              "y":120},
            "size":{
              "width":300,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1d6652d9d614ab78a6694a5087cb177",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":730,
                  "y":120},
                "size":{
                  "width":300,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c98b02bf93d847c1a831c78c48a2eace",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":408,
              "y":42},
            "size":{
              "width":312,
              "height":2048}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fb0b887d053451581ede8d1dcc67bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":408,
                  "y":42},
                "size":{
                  "width":312,
                  "height":2048}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页v5/u0.jpg"}},
{
          "id":"22764929b0134508b299780533202201",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":450,
              "y":260},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed5ba8684df8424b8768177f86cfbe0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":450,
                  "y":260},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约/u4.png"}},
{
          "id":"e47853f1edec4fdb94c040b1fbc3c3de",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":310},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约/u6_line.png"}},
{
          "id":"1fb6769226344f66ab4000ed0566d346",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":545,
              "y":317},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约/u7_line.png"}},
{
          "id":"d2dfd3634419409ab7a48097989e5f84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":481,
              "y":328},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0b0a1e412324ef4bdabe56f85bb169e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":481,
                  "y":328},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2e28a5607124a058cab4783bb257706",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":580,
              "y":328},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a807ff0550854f4ba433c3f7184a5113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":580,
                  "y":328},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bca484e54b554dfba1d77144d9332243",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":453,
              "y":266},
            "size":{
              "width":190,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75b7ae5659414544bb0e58fbef8655fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":453,
                  "y":266},
                "size":{
                  "width":190,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfff7536606a42f2976e70cfe29d4beb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":50},
            "size":{
              "width":320,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0237555b267e43988b95738d5ceec9dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":50},
                "size":{
                  "width":320,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定时退出/u0.png"}},
{
          "id":"d22c1bbcbbcf42478c57a4108f8c9df0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":50},
            "size":{
              "width":320,
              "height":274}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"019efb37e95e4342b25900135b8dc3bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":50},
                "size":{
                  "width":320,
                  "height":274}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/直播播放/u2.png"}},
{
          "id":"0da4a10fafeb4d1fb3f158673df68181",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":50},
            "size":{
              "width":320,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6415edd8201c450585c2b9e63212997c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":50},
                "size":{
                  "width":320,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定时退出/u2.png"}},
{
          "id":"f06399b0b89b4e30beadf9f7dd331dc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "location":{
              "x":43,
              "y":73},
            "size":{
              "width":20,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2496077879c43d28294e6da66ffd941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "location":{
                  "x":43,
                  "y":73},
                "size":{
                  "width":20,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54831c70f0994930a67e9758e8d011fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":93,
              "y":80},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0ae7247de2c4a6190f8ec39a1f95023",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":93,
                  "y":80},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5c9f313ed8e42369ba6bd732ecc440e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":314,
              "y":75},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adcffa63e18445d88a7c338d598f1aa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":314,
                  "y":75},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/直播播放/u10.png"}},
{
          "id":"f086c63a1923489f85b414ccef391c0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":33,
              "y":334},
            "size":{
              "width":320,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc246649a11540e68ca6eaf9c4258e4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":33,
                  "y":334},
                "size":{
                  "width":320,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放状态滑动列表/u2.png"}},
{
          "id":"9ac1d0f4fb4a4d0d96fdd711b6949599",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":175,
              "y":344},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e592b9bfeb746629af2ff1a7f62416b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":175,
                  "y":344},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放状态滑动列表/u4.png"}},
{
          "id":"943b477a79c74f4d913af2e961d0f612",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":380},
            "size":{
              "width":318,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ef6fdd0e5d04f73a1db0d50ffde8892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":380},
                "size":{
                  "width":318,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放状态滑动列表/u10.png"}},
{
          "id":"c10a893fc0224ccbb6f4b087fc1213a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":381},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c96ae6fa2354d9a8b2f4e693ff48098",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":381},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放状态滑动列表/u12.png"}},
{
          "id":"0ba9bdde895249c8a6d27146c7aa4f24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":91,
              "y":386},
            "size":{
              "width":168,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6145f11c4f2a45988ce60d46b419398e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":91,
                  "y":386},
                "size":{
                  "width":168,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cefd05db2d3b4ab98b3e0ead04c80749",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":92,
              "y":408},
            "size":{
              "width":80,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbb078f09479402db639c8a70a8999b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":408},
                "size":{
                  "width":80,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b9098970fea43449d1351853bd557aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "location":{
              "x":289,
              "y":395},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d16107116aa418393c6bd4687aaa397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "location":{
                  "x":289,
                  "y":395},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46411c1b241e4a648f29d07cfbe5e0a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":64,
              "y":439},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dc03862c1434a04b235f49bd0887bbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":64,
                  "y":439},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d666863a0184ac28459eab27e04a7bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":460},
            "size":{
              "width":318,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/播放状态滑动列表/u22_line.png"}},
{
          "id":"225f96f8b90e4985ae15e2c31318cf1e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":460},
            "size":{
              "width":138,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/播放状态滑动列表/u23_line.png"}},
{
          "id":"3b13a6d0c0974f51bb1426118c3dbb2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":247,
              "y":440},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38c8b6c60984452bb615dd2c29bd67d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":247,
                  "y":440},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f696535966374934aaf94107795a7523",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":490},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/播放状态滑动列表/u26_line.png"}},
{
          "id":"4decbdf81d3c4faa9db236dea2c9719a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":53,
              "y":475},
            "size":{
              "width":323,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32bec570489842da89e8468bf873a7f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":53,
                  "y":475},
                "size":{
                  "width":323,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08b30a260f3a4f76886d0f00454b6968",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":520},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/播放状态滑动列表/u26_line.png"}},
{
          "id":"d311e683ca2b4593b9831c404d9fb081",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":551},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/播放状态滑动列表/u26_line.png"}},
{
          "id":"a2759e2fb8b7494591e090abda1dcce3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":35,
              "y":583},
            "size":{
              "width":318,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f790528acbad4475b4d8cfcb63ae71ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":35,
                  "y":583},
                "size":{
                  "width":318,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放状态滑动列表/u37.png"}},
{
          "id":"324cb94f992f434dbb765ab78f93b5a4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":576},
            "size":{
              "width":318,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/播放状态滑动列表/u26_line.png"}},
{
          "id":"0bf3d497311b44219c98cb138e303a76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":583},
            "size":{
              "width":48,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"322de6943d8f4bd1911f19b56757230f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":583},
                "size":{
                  "width":48,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放状态滑动列表/u40.png"}},
{
          "id":"488bd271873c4583b0f2c94329758276",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":178,
              "y":583},
            "size":{
              "width":48,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc3d361df02c497ab05cd52f1b701d4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":178,
                  "y":583},
                "size":{
                  "width":48,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放状态滑动列表/u40.png"}},
{
          "id":"329072975fd4475cae2eac19820e225f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":305,
              "y":582},
            "size":{
              "width":48,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2a7d5e767bd4cc6a9534ecc6d193ce2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":305,
                  "y":582},
                "size":{
                  "width":48,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放状态滑动列表/u40.png"}},
{
          "id":"afd5d5ab515849c1bf8282084206acc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":216,
              "y":584},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"975ccc01db6344c9a51944271b4cfc71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":216,
                  "y":584},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2729c09171346db96f720ac675260dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":53,
              "y":501},
            "size":{
              "width":220,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a529d6128d84f2d825acd7396515e3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":53,
                  "y":501},
                "size":{
                  "width":220,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e37d74c49424154a963a008ecbc11f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":53,
              "y":530},
            "size":{
              "width":323,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a374843845943038ffeb951f49a5478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":53,
                  "y":530},
                "size":{
                  "width":323,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae10037cabdc4221b1a59b3baba2b3cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":53,
              "y":559},
            "size":{
              "width":323,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f1097c036eb4c36858de8f60d0eaee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":53,
                  "y":559},
                "size":{
                  "width":323,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d2181854f58487bbbee9ee83e5d63ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":289,
              "y":500},
            "size":{
              "width":39,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"918c9edbb1484fcfbd135276189a9213",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":289,
                  "y":500},
                "size":{
                  "width":39,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/直播播放/u46.png"}},
{
          "id":"41d4b133f61e427da8991860e805eb8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":289,
              "y":530},
            "size":{
              "width":39,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c45c3221c8e4b2eb96d2e97e6306ac4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":289,
                  "y":530},
                "size":{
                  "width":39,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/直播播放/u46.png"}},
{
          "id":"3ae6191b82f6406ea5cd88d9a081c908",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":289,
              "y":560},
            "size":{
              "width":39,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"504185734c2543f8a456b60e2c7a7c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":289,
                  "y":560},
                "size":{
                  "width":39,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/直播播放/u50.png"}},
{
          "id":"8cc9f2d53be54f59b07e03a769e7d719",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":79,
              "y":298},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f11e8f32eeb346288a36e3eb3c3989c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":79,
                  "y":298},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约/u4.png"}},
{
          "id":"c7d5acc872364f10a77b525149a41683",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":82,
              "y":325},
            "size":{
              "width":190,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f8970d52d484e57a05bccb9f55d714b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":82,
                  "y":325},
                "size":{
                  "width":190,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b94cae60e0604f7990541efc34e8ae22":{
      "scriptId":"u0"},
    "e1d6652d9d614ab78a6694a5087cb177":{
      "scriptId":"u1"},
    "c98b02bf93d847c1a831c78c48a2eace":{
      "scriptId":"u2"},
    "7fb0b887d053451581ede8d1dcc67bd2":{
      "scriptId":"u3"},
    "22764929b0134508b299780533202201":{
      "scriptId":"u4"},
    "ed5ba8684df8424b8768177f86cfbe0f":{
      "scriptId":"u5"},
    "e47853f1edec4fdb94c040b1fbc3c3de":{
      "scriptId":"u6"},
    "1fb6769226344f66ab4000ed0566d346":{
      "scriptId":"u7"},
    "d2dfd3634419409ab7a48097989e5f84":{
      "scriptId":"u8"},
    "e0b0a1e412324ef4bdabe56f85bb169e":{
      "scriptId":"u9"},
    "b2e28a5607124a058cab4783bb257706":{
      "scriptId":"u10"},
    "a807ff0550854f4ba433c3f7184a5113":{
      "scriptId":"u11"},
    "bca484e54b554dfba1d77144d9332243":{
      "scriptId":"u12"},
    "75b7ae5659414544bb0e58fbef8655fb":{
      "scriptId":"u13"},
    "dfff7536606a42f2976e70cfe29d4beb":{
      "scriptId":"u14"},
    "0237555b267e43988b95738d5ceec9dc":{
      "scriptId":"u15"},
    "d22c1bbcbbcf42478c57a4108f8c9df0":{
      "scriptId":"u16"},
    "019efb37e95e4342b25900135b8dc3bc":{
      "scriptId":"u17"},
    "0da4a10fafeb4d1fb3f158673df68181":{
      "scriptId":"u18"},
    "6415edd8201c450585c2b9e63212997c":{
      "scriptId":"u19"},
    "f06399b0b89b4e30beadf9f7dd331dc4":{
      "scriptId":"u20"},
    "b2496077879c43d28294e6da66ffd941":{
      "scriptId":"u21"},
    "54831c70f0994930a67e9758e8d011fd":{
      "scriptId":"u22"},
    "b0ae7247de2c4a6190f8ec39a1f95023":{
      "scriptId":"u23"},
    "f5c9f313ed8e42369ba6bd732ecc440e":{
      "scriptId":"u24"},
    "adcffa63e18445d88a7c338d598f1aa1":{
      "scriptId":"u25"},
    "f086c63a1923489f85b414ccef391c0b":{
      "scriptId":"u26"},
    "cc246649a11540e68ca6eaf9c4258e4b":{
      "scriptId":"u27"},
    "9ac1d0f4fb4a4d0d96fdd711b6949599":{
      "scriptId":"u28"},
    "8e592b9bfeb746629af2ff1a7f62416b":{
      "scriptId":"u29"},
    "943b477a79c74f4d913af2e961d0f612":{
      "scriptId":"u30"},
    "0ef6fdd0e5d04f73a1db0d50ffde8892":{
      "scriptId":"u31"},
    "c10a893fc0224ccbb6f4b087fc1213a9":{
      "scriptId":"u32"},
    "4c96ae6fa2354d9a8b2f4e693ff48098":{
      "scriptId":"u33"},
    "0ba9bdde895249c8a6d27146c7aa4f24":{
      "scriptId":"u34"},
    "6145f11c4f2a45988ce60d46b419398e":{
      "scriptId":"u35"},
    "cefd05db2d3b4ab98b3e0ead04c80749":{
      "scriptId":"u36"},
    "dbb078f09479402db639c8a70a8999b4":{
      "scriptId":"u37"},
    "9b9098970fea43449d1351853bd557aa":{
      "scriptId":"u38"},
    "1d16107116aa418393c6bd4687aaa397":{
      "scriptId":"u39"},
    "46411c1b241e4a648f29d07cfbe5e0a4":{
      "scriptId":"u40"},
    "4dc03862c1434a04b235f49bd0887bbf":{
      "scriptId":"u41"},
    "5d666863a0184ac28459eab27e04a7bf":{
      "scriptId":"u42"},
    "225f96f8b90e4985ae15e2c31318cf1e":{
      "scriptId":"u43"},
    "3b13a6d0c0974f51bb1426118c3dbb2c":{
      "scriptId":"u44"},
    "38c8b6c60984452bb615dd2c29bd67d6":{
      "scriptId":"u45"},
    "f696535966374934aaf94107795a7523":{
      "scriptId":"u46"},
    "4decbdf81d3c4faa9db236dea2c9719a":{
      "scriptId":"u47"},
    "32bec570489842da89e8468bf873a7f6":{
      "scriptId":"u48"},
    "08b30a260f3a4f76886d0f00454b6968":{
      "scriptId":"u49"},
    "d311e683ca2b4593b9831c404d9fb081":{
      "scriptId":"u50"},
    "a2759e2fb8b7494591e090abda1dcce3":{
      "scriptId":"u51"},
    "f790528acbad4475b4d8cfcb63ae71ad":{
      "scriptId":"u52"},
    "324cb94f992f434dbb765ab78f93b5a4":{
      "scriptId":"u53"},
    "0bf3d497311b44219c98cb138e303a76":{
      "scriptId":"u54"},
    "322de6943d8f4bd1911f19b56757230f":{
      "scriptId":"u55"},
    "488bd271873c4583b0f2c94329758276":{
      "scriptId":"u56"},
    "cc3d361df02c497ab05cd52f1b701d4f":{
      "scriptId":"u57"},
    "329072975fd4475cae2eac19820e225f":{
      "scriptId":"u58"},
    "e2a7d5e767bd4cc6a9534ecc6d193ce2":{
      "scriptId":"u59"},
    "afd5d5ab515849c1bf8282084206acc8":{
      "scriptId":"u60"},
    "975ccc01db6344c9a51944271b4cfc71":{
      "scriptId":"u61"},
    "d2729c09171346db96f720ac675260dd":{
      "scriptId":"u62"},
    "8a529d6128d84f2d825acd7396515e3c":{
      "scriptId":"u63"},
    "9e37d74c49424154a963a008ecbc11f8":{
      "scriptId":"u64"},
    "3a374843845943038ffeb951f49a5478":{
      "scriptId":"u65"},
    "ae10037cabdc4221b1a59b3baba2b3cd":{
      "scriptId":"u66"},
    "7f1097c036eb4c36858de8f60d0eaee0":{
      "scriptId":"u67"},
    "1d2181854f58487bbbee9ee83e5d63ee":{
      "scriptId":"u68"},
    "918c9edbb1484fcfbd135276189a9213":{
      "scriptId":"u69"},
    "41d4b133f61e427da8991860e805eb8c":{
      "scriptId":"u70"},
    "3c45c3221c8e4b2eb96d2e97e6306ac4":{
      "scriptId":"u71"},
    "3ae6191b82f6406ea5cd88d9a081c908":{
      "scriptId":"u72"},
    "504185734c2543f8a456b60e2c7a7c8c":{
      "scriptId":"u73"},
    "8cc9f2d53be54f59b07e03a769e7d719":{
      "scriptId":"u74"},
    "f11e8f32eeb346288a36e3eb3c3989c2":{
      "scriptId":"u75"},
    "c7d5acc872364f10a77b525149a41683":{
      "scriptId":"u76"},
    "1f8970d52d484e57a05bccb9f55d714b":{
      "scriptId":"u77"}}});