$axure.loadCurrentPage({
  "url":"首页v5.html",
  "generationDate":new Date(1392283797956.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"37e0d89d724d4fd292285b58f2da3756",
    "type":"Axure:Page",
    "name":"首页V5",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3c2fb7108a9c46ce9023819b49c58af1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":224,
              "y":36},
            "size":{
              "width":312,
              "height":2048}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae0d0e85d524d3bace501c8d142ec2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":224,
                  "y":36},
                "size":{
                  "width":312,
                  "height":2048}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页v5/u0.jpg"}},
{
          "id":"ac5231163c4d4ac185d2b1a838b168d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":60,
              "y":110},
            "size":{
              "width":80,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b4df0616aa4ce7b4ac07b38aa105a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":60,
                  "y":110},
                "size":{
                  "width":80,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d236b3b8c82149aebacfa67796e07a79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":539,
              "y":198},
            "size":{
              "width":161,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ced79e6517f4943bd8731af655469c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":539,
                  "y":198},
                "size":{
                  "width":161,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b8c0d1291354426a32d173a88b945fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":42,
              "y":329},
            "size":{
              "width":100,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5ee21fce03440a2998e5b0c0fc3545c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":42,
                  "y":329},
                "size":{
                  "width":100,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e38925c0561c480ea5c4b4aecec5186e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":348},
            "size":{
              "width":114,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/首页v5/u8_end.png",
            "line~":"images/首页v5/u8_line.png"}},
{
          "id":"4523de38253443b0b5533d85db1d850c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":45,
              "y":594},
            "size":{
              "width":114,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4debe717cec543e2b9fafbc338f377c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":45,
                  "y":594},
                "size":{
                  "width":114,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02f9d586e5fa4b618993cf782df6eb70",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":603},
            "size":{
              "width":114,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/首页v5/u8_end.png",
            "line~":"images/首页v5/u8_line.png"}},
{
          "id":"66669c4315444e398c50b4cc957dbc46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":44,
              "y":482},
            "size":{
              "width":136,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9734cacacce444e3942b9d27abc186ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":44,
                  "y":482},
                "size":{
                  "width":136,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b81a756eadfc48329c52e6afc91f0a43",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":506},
            "size":{
              "width":114,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/首页v5/u8_end.png",
            "line~":"images/首页v5/u8_line.png"}},
{
          "id":"acba12eefb0f49a6ad55e239a696132d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":48,
              "y":1728},
            "size":{
              "width":114,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2cfee8bd33f4ad1b4d86b22ff1b71a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":48,
                  "y":1728},
                "size":{
                  "width":114,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"460b49ba48854cd4b0a5dceff2a3901f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":1745},
            "size":{
              "width":114,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/首页v5/u8_end.png",
            "line~":"images/首页v5/u8_line.png"}},
{
          "id":"acd0eb6b119d47619a3ea5a1f9f87109",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":42,
              "y":2049},
            "size":{
              "width":114,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b3d90d4eee746c18cbf893a6b9a3eba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":42,
                  "y":2049},
                "size":{
                  "width":114,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f1a6c9bf3b94a5da9a3aa89e2a497d3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":2063},
            "size":{
              "width":114,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/首页v5/u8_end.png",
            "line~":"images/首页v5/u8_line.png"}},
{
          "id":"940c07296e0842d9b6b33691d7ed06b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":42,
              "y":2120},
            "size":{
              "width":420,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b8a5c60a3324b32bfc8ee4d656327f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":42,
                  "y":2120},
                "size":{
                  "width":420,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44ccb743c132432e96fd18a0e31fb4e5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":110},
            "size":{
              "width":127,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/首页v5/u8_end.png",
            "line~":"images/首页v5/u23_line.png"}},
{
          "id":"e71eba4d93f94dc4b3a6787d0f1facbb",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":300,
              "y":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34009a460b784c03ad7cb5d9fb9afc7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":300,
                  "y":120}},
              "adaptiveStyles":{
}}]},
{
          "id":"6b18217f146b4c7f81581f88c432c453",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":529,
              "y":110},
            "size":{
              "width":51,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/首页v5/u26_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页v5/u26_line.png"}},
{
          "id":"64b6d5aad8124b7fa437baf94d97c64d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":580,
              "y":110},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3b69e4b773b4769aaff65b5873c69b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":580,
                  "y":110},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f200aa71237d4da0a9762684cae9d788",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":530,
              "y":146},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39bc6f7db922445bb63ef8e756dc756b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":530,
                  "y":146},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d465738d90c343f1bbc2b2d4db7971bf",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":350,
              "y":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf1b824cb2b4331bad343d7e7ff8352",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":350,
                  "y":120}},
              "adaptiveStyles":{
}}]},
{
          "id":"ffc58e330bce4472a060a9f120810870",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":516,
              "y":440},
            "size":{
              "width":64,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/首页v5/u33_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页v5/u33_line.png"}},
{
          "id":"d4de93333656454dafb14f76e008dbf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":580,
              "y":440},
            "size":{
              "width":71,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b775ce94ed7c46d3b67881f60e8e62e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":580,
                  "y":440},
                "size":{
                  "width":71,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3c2fb7108a9c46ce9023819b49c58af1":{
      "scriptId":"u0"},
    "9ae0d0e85d524d3bace501c8d142ec2e":{
      "scriptId":"u1"},
    "ac5231163c4d4ac185d2b1a838b168d0":{
      "scriptId":"u2"},
    "c9b4df0616aa4ce7b4ac07b38aa105a3":{
      "scriptId":"u3"},
    "d236b3b8c82149aebacfa67796e07a79":{
      "scriptId":"u4"},
    "0ced79e6517f4943bd8731af655469c0":{
      "scriptId":"u5"},
    "0b8c0d1291354426a32d173a88b945fb":{
      "scriptId":"u6"},
    "c5ee21fce03440a2998e5b0c0fc3545c":{
      "scriptId":"u7"},
    "e38925c0561c480ea5c4b4aecec5186e":{
      "scriptId":"u8"},
    "4523de38253443b0b5533d85db1d850c":{
      "scriptId":"u9"},
    "4debe717cec543e2b9fafbc338f377c2":{
      "scriptId":"u10"},
    "02f9d586e5fa4b618993cf782df6eb70":{
      "scriptId":"u11"},
    "66669c4315444e398c50b4cc957dbc46":{
      "scriptId":"u12"},
    "9734cacacce444e3942b9d27abc186ba":{
      "scriptId":"u13"},
    "b81a756eadfc48329c52e6afc91f0a43":{
      "scriptId":"u14"},
    "acba12eefb0f49a6ad55e239a696132d":{
      "scriptId":"u15"},
    "f2cfee8bd33f4ad1b4d86b22ff1b71a2":{
      "scriptId":"u16"},
    "460b49ba48854cd4b0a5dceff2a3901f":{
      "scriptId":"u17"},
    "acd0eb6b119d47619a3ea5a1f9f87109":{
      "scriptId":"u18"},
    "6b3d90d4eee746c18cbf893a6b9a3eba":{
      "scriptId":"u19"},
    "3f1a6c9bf3b94a5da9a3aa89e2a497d3":{
      "scriptId":"u20"},
    "940c07296e0842d9b6b33691d7ed06b1":{
      "scriptId":"u21"},
    "0b8a5c60a3324b32bfc8ee4d656327f5":{
      "scriptId":"u22"},
    "44ccb743c132432e96fd18a0e31fb4e5":{
      "scriptId":"u23"},
    "e71eba4d93f94dc4b3a6787d0f1facbb":{
      "scriptId":"u24"},
    "34009a460b784c03ad7cb5d9fb9afc7f":{
      "scriptId":"u25"},
    "6b18217f146b4c7f81581f88c432c453":{
      "scriptId":"u26"},
    "64b6d5aad8124b7fa437baf94d97c64d":{
      "scriptId":"u27"},
    "f3b69e4b773b4769aaff65b5873c69b9":{
      "scriptId":"u28"},
    "f200aa71237d4da0a9762684cae9d788":{
      "scriptId":"u29"},
    "39bc6f7db922445bb63ef8e756dc756b":{
      "scriptId":"u30"},
    "d465738d90c343f1bbc2b2d4db7971bf":{
      "scriptId":"u31"},
    "adf1b824cb2b4331bad343d7e7ff8352":{
      "scriptId":"u32"},
    "ffc58e330bce4472a060a9f120810870":{
      "scriptId":"u33"},
    "d4de93333656454dafb14f76e008dbf4":{
      "scriptId":"u34"},
    "b775ce94ed7c46d3b67881f60e8e62e6":{
      "scriptId":"u35"}}});