$axure.loadCurrentPage({
  "url":"订阅.html",
  "generationDate":new Date(1392372079253.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0f9c1f52f9e74704bd4e8b7f72af6f93",
    "type":"Axure:Page",
    "name":"订阅",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0cffbc412dcb413786305bb21603f8a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":690,
              "y":198},
            "size":{
              "width":320,
              "height":432}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60b0ac92e551422eaf1b5fc0e4c8064a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":690,
                  "y":198},
                "size":{
                  "width":320,
                  "height":432}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"873c83b87ced418dbbbc05edb65c5d2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":34},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde457f4b2454e4c9d51ab0fda20369c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":34},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订阅/u2.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "0cffbc412dcb413786305bb21603f8a6":{
      "scriptId":"u0"},
    "60b0ac92e551422eaf1b5fc0e4c8064a":{
      "scriptId":"u1"},
    "873c83b87ced418dbbbc05edb65c5d2b":{
      "scriptId":"u2"},
    "bde457f4b2454e4c9d51ab0fda20369c":{
      "scriptId":"u3"}}});